[package]
name = "xed"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
paste = "1.0.14"
xed-sys = "0.5"

[dev-dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.0", features = ["derive", "wrap_help"] }
hex = "0.4.3"
